In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [3]:
data = np.loadtxt("Data/4_4_2_10.000000_5.000000_1.000000_1000000000_0_1D_can_SWAP.dat")
np.shape(data)
data[:4]

array([[98., 64., 39.],
       [66., 69., 66.],
       [75., 66., 60.],
       [61., 76., 64.]])

In [4]:
P = np.sum(data,axis=0)
P

array([1725621., 1432859., 1411456.])

In [5]:
pj = np.zeros(data.shape)
pj

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj

array([[1725621., 1432859., 1411456.],
       [1725621., 1432859., 1411456.],
       [1725621., 1432859., 1411456.],
       ...,
       [1725621., 1432859., 1411456.],
       [1725621., 1432859., 1411456.],
       [1725621., 1432859., 1411456.]])

In [7]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [8]:
l_A=1
S = -np.log(pj_bar[:,l_A]/pj_bar[:,0])
S

array([0.18590311, 0.18592515, 0.18591784, ..., 0.18590911, 0.18593502,
       0.18592247])

In [9]:
S_mean = np.mean(S)
S_mean

0.18591523666656026

In [10]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.001573087768016042

In [11]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 0.185915 +/- 0.001573
