In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [75]:
data = np.loadtxt("4_4_2_1.000000_3.000000_1.000000_1000000000_0_1D_can_SWAP.dat")
np.shape(data)
data[:4]

array([[116.,  44.,  41.],
       [130.,  49.,  22.],
       [110.,  55.,  36.],
       [129.,  51.,  21.]])

In [76]:
P = np.sum(data,axis=0)
P

array([722657., 261365., 231425.])

In [77]:
pj = np.zeros(data.shape)
pj

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj

array([[722657., 261365., 231425.],
       [722657., 261365., 231425.],
       [722657., 261365., 231425.],
       ...,
       [722657., 261365., 231425.],
       [722657., 261365., 231425.],
       [722657., 261365., 231425.]])

In [79]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [80]:
l_A=2
S = -np.log(pj_bar[:,l_A]/pj_bar[:,0])
S

array([1.1386955 , 1.13859401, 1.13868219, ..., 1.13883451, 1.13864985,
       1.13880304])

In [81]:
S_mean = np.mean(S)
S_mean

1.1386788536079153

In [82]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.008365323859292987