In [119]:
import matplotlib.pyplot as plt
import numpy as np

In [120]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [121]:
data = np.loadtxt("3_9_2_21.000000D_3.000000_1.000000_100000000_326_can_SWAP.dat")
np.shape(data)
data[:4]

array([[134.,  29.,  28.,   9.,   1.],
       [ 66.,  10.,  18.,  61.,  46.],
       [116.,  21.,  20.,  27.,  17.],
       [ 84.,  20.,  33.,  16.,  48.]])

In [122]:
P = np.sum(data,axis=0)
P

array([63245., 21431., 16342., 13833., 13990.])

In [123]:
pj = np.zeros(data.shape)
pj[:10]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [124]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj[:10]

array([[63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.],
       [63245., 21431., 16342., 13833., 13990.]])

In [125]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [126]:
l_A = 2
D = 2
S = -np.log(pj_bar[:,l_A**D]/pj_bar[:,0])
S[:10]

array([1.50662377, 1.51092266, 1.50805336, 1.51078116, 1.50817656,
       1.5087927 , 1.50983497, 1.50952259, 1.50713839, 1.50682241])

In [127]:
S_mean = np.mean(S)
S_mean

1.508674683397806

In [128]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.05276206549991632

In [129]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 1.508675 +/- 0.052762


In [130]:
np.mean([1.635206,1.508675,1.647279,1.568805])

1.58999125