In [17]:
import matplotlib.pyplot as plt
import numpy as np

In [18]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [30]:
data = np.loadtxt("2_8_1_2D_1.000000_2.000000_1.000000_100000000_17_can_SWAP.dat")
np.shape(data)
data[:4]

array([[801., 200.],
       [600., 401.],
       [926.,  75.],
       [490., 511.]])

In [31]:
P = np.sum(data,axis=0)
P

array([810788., 207229.])

In [32]:
pj = np.zeros(data.shape)

In [33]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]

In [34]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [35]:
l_A = 1
D = 2
m_A = l_A**2
S = -np.log(pj_bar[:,m_A]/pj_bar[:,0])
S[:10]

array([1.36415932, 1.36537879, 1.36340138, 1.36604654, 1.36334683,
       1.36406835, 1.36439586, 1.36512997, 1.36294679, 1.36294679])

In [36]:
S_mean = np.mean(S)
S_mean

1.3641824190074854

In [37]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.030234770645389313

In [38]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 1.364182 +/- 0.030235


In [39]:
np.mean([1.582970,1.577933,1.574760,1.575610,1.588356])

1.5799258000000003

In [40]:
np.std([1.582970,1.577933,1.574760,1.575610,1.588356])

0.005091528194952917