In [310]:
import matplotlib.pyplot as plt
import numpy as np

In [311]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [357]:
data = np.loadtxt("Data/2_2_1_10.000000_5.000000_1.000000_1000000000_0_1D_can_SWAP.dat")
np.shape(data)
data[:4]

array([[ 89., 112.],
       [ 98., 103.],
       [111.,  90.],
       [101., 100.]])

In [358]:
P = np.sum(data,axis=0)
P

array([5818350., 4646313.])

In [359]:
pj = np.zeros(data.shape)
pj

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [360]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj

array([[5818350., 4646313.],
       [5818350., 4646313.],
       [5818350., 4646313.],
       ...,
       [5818350., 4646313.],
       [5818350., 4646313.],
       [5818350., 4646313.]])

In [361]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [362]:
l_A=1
S = -np.log(pj_bar[:,l_A]/pj_bar[:,0])
S

array([0.22495152, 0.22494804, 0.22494301, ..., 0.2249403 , 0.22493217,
       0.22494417])

In [363]:
S_mean = np.mean(S)
S_mean

0.22494271453600784

In [364]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.0013346935803246747

In [365]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 0.224943 +/- 0.001335
