In [216]:
import matplotlib.pyplot as plt
import numpy as np

In [217]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [218]:
data = np.loadtxt("2_2_1_1.000000_2.000000_1.000000_100000000_0_1D_can_SWAP.dat")
np.shape(data)
data[:4]

array([[103.,  98.],
       [162.,  39.],
       [122.,  79.],
       [142.,  59.]])

In [219]:
P = np.sum(data,axis=0)
P

array([866352., 356532.])

In [220]:
pj = np.zeros(data.shape)
pj[:10]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [221]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj[:10]

array([[866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.],
       [866352., 356532.]])

In [222]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [224]:
l_A=1
S = -np.log(pj_bar[:,l_A]/pj_bar[:,0])
S[:10]

array([0.88802331, 0.88778968, 0.88794807, 0.88786887, 0.88787679,
       0.88791639, 0.88784115, 0.88783324, 0.88779364, 0.88796787])

In [225]:
S_mean = np.mean(S)
S_mean

0.8878672969371981

In [226]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.007335750729362104

In [227]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 0.887867 +/- 0.007336
