In [36]:
import matplotlib.pyplot as plt
import numpy as np

In [37]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [38]:
data = np.loadtxt("4_4_2_1.000000_2.000000_1.000000_100000000_0_1D_can_SWAP.dat")
np.shape(data)
data[:4]

array([[103.,  53.,  45.],
       [ 91.,  34.,  76.],
       [160.,  22.,  19.],
       [110.,  47.,  44.]])

In [39]:
P = np.sum(data,axis=0)
P

array([227855.,  82790.,  74471.])

In [40]:
pj = np.zeros(data.shape)
pj[:10]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj[:10]

array([[227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.],
       [227855.,  82790.,  74471.]])

In [42]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [43]:
l_A=2
S = -np.log(pj_bar[:,l_A]/pj_bar[:,0])
S[:10]

array([1.11845197, 1.11892127, 1.11785239, 1.1184078 , 1.11878328,
       1.11860364, 1.11821585, 1.11806034, 1.11855455, 1.11758996])

In [44]:
S_mean = np.mean(S)
S_mean

1.1182997173110893

In [45]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.01764397464073646

In [46]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 1.118300 +/- 0.017644
