In [443]:
import matplotlib.pyplot as plt
import numpy as np

In [444]:
np.set_printoptions(precision=8)

### $\beta$-scaling (but the original estimator)

In [445]:
data = np.loadtxt("3_9_2_1.000000_4.000000_1.000000_100000000_0_2D_can_SWAP.dat")
np.shape(data)
data[:4]

array([[ 87.,  19.,  49.,  16.,  30.],
       [130.,  14.,  22.,  14.,  21.],
       [ 99.,  33.,  35.,  19.,  15.],
       [ 99.,  25.,  10.,  22.,  45.]])

In [446]:
P = np.sum(data,axis=0)
P

array([22949.,  7380.,  6153.,  4495.,  4650.])

In [447]:
pj = np.zeros(data.shape)
pj[:10]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [448]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj[:10]

array([[22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.],
       [22949.,  7380.,  6153.,  4495.,  4650.]])

In [449]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [450]:
l_A = 1
D = 2
S = -np.log(pj_bar[:,l_A**D]/pj_bar[:,0])
S[:10]

array([1.13328035, 1.1307187 , 1.13465905, 1.13357076, 1.13562554,
       1.13077972, 1.13504311, 1.13599982, 1.13601481, 1.13535902])

In [451]:
S_mean = np.mean(S)
S_mean

1.1345015413827588

In [452]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.036946922164083254

In [453]:
print(f'S2 = {S_mean:.6f} +/- {S_err:.6f}')

S2 = 1.134502 +/- 0.036947


In [455]:
1.134502 - 0.036947

1.0975549999999998