In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
data = np.loadtxt("4_4_2_1D_1.000000_1.000000_1.000000_10000000_42_can_Pn_2-mA.dat")

In [14]:
np.sum(data,axis=1)

array([1262., 1070., 1000., 1160., 1280., 1112., 1240., 1258., 1300.,
       1080., 1380., 1320., 1022., 1232., 1286., 1308., 1136., 1142.,
       1088., 1226., 1210., 1144., 1118.,  902., 1314., 1016., 1354.,
       1260., 1322., 1290., 1222.,  988., 1262., 1098., 1332., 1168.,
       1232.,  772., 1256., 1094., 1314., 1294., 1246., 1308.,  906.,
       1088., 1138.,  874., 1002., 1502., 1096., 1412., 1172., 1140.,
       1306., 1286., 1314., 1242., 1232., 1404., 1222., 1150., 1254.,
       1162., 1160., 1050., 1116., 1248., 1344., 1002., 1116., 1512.,
       1184., 1110., 1322.])

In [15]:
# Trick to broadcast the above array
# Will allow to divide each data row by norm
row_wise_norms = np.sum(data,axis=1)[:,None]

In [16]:
Pns = data/row_wise_norms;

In [17]:
# Check normalization
np.sum(Pns,axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [18]:
Pns_mean = np.mean(Pns,axis=0)
Pns_mean

array([0.03853222, 0.2429411 , 0.43413859, 0.2443458 , 0.04004229])

In [48]:
# Normalize after doing the Jacknife
# Don't do row-wise normalization