In [138]:
import matplotlib.pyplot as plt
import numpy as np

In [139]:
np.set_printoptions(precision=8)

In [140]:
path="/Users/ecasiano/Xcode/pimc/pimc/TestNewSWAPn/"
path="/Users/ecasiano/Desktop/PrototypeScripts/TestData/"

In [141]:
seed = 310

In [142]:
data_Pn_squared_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_PnSquared-mA1_"+str(seed)+".dat")
data_Pn_squared_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_PnSquared-mA2_"+str(seed)+".dat")

data = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_PnSquared-mA2_310.dat")
data_sum = np.sum(data,axis=0)
# data_SWAPn_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAPn-mA1_"+str(seed)+".dat")
# data_SWAPn_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAPn-mA2_"+str(seed)+".dat")

# data_SWAPn_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n0_310.dat")

In [143]:
data_sum.astype(int)

array([    4701,  1998887, 18441703,  1990100,     3956])

In [144]:
dataSWAPn0 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n0_310.dat")
dataSWAPn1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n1_310.dat")
dataSWAPn2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n2_310.dat")
dataSWAPn3 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n3_310.dat")
dataSWAPn4 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n4_310.dat")

In [152]:
np.sum(dataSWAPn0,axis=0)

array([      0., 1790585.,    4650.])

In [153]:
dataSWAPn = np.zeros(5)
dataSWAPn[0] = np.sum(dataSWAPn0[:,1],axis=0)
dataSWAPn[1] = np.sum(dataSWAPn1[:,1],axis=0)
dataSWAPn[2] = np.sum(dataSWAPn2[:,1],axis=0)
dataSWAPn[3] = np.sum(dataSWAPn3[:,1],axis=0)
dataSWAPn[4] = np.sum(dataSWAPn4[:,1],axis=0)

In [155]:
dataSWAPn.astype(int)

array([ 1790585, 21391964,  1564135,     2378,        0])

In [157]:
-np.log(dataSWAPn.astype(int)/data_sum.astype(int))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-5.94252241, -2.37042481,  2.46728161,  6.72968037,         inf])

In [107]:
Pn_squared_m1_col_sum = np.sum(data_Pn_squared_m1,axis=0)
Pn_squared_m2_col_sum = np.sum(data_Pn_squared_m2,axis=0)

SWAPn_m1_col_sum = np.sum(data_SWAPn_m1,axis=0)
SWAPn_m2_col_sum = np.sum(data_SWAPn_m2,axis=0)

In [86]:
SWAPn_m2_col_sum.astype(int),Pn_squared_m2_col_sum.astype(int)

(array([    49844,  19699140, 183907242,  19731613,     50045]),
 array([    49828,  20170529, 185077593,  20035141,     48668]))

In [87]:
-np.log(SWAPn_m2_col_sum.astype(int)/Pn_squared_m2_col_sum.astype(int))

array([-0.00032105,  0.0236476 ,  0.00634365,  0.01526571, -0.02790087])

In [88]:
SWAPn_m2_col_sum[0]-SWAPn_m2_col_sum[-1],Pn_squared_m2_col_sum[0]-Pn_squared_m2_col_sum[-1]

(-201.0, 1160.0)

In [43]:
# -np.log(np.mean(data_SWAPn_m2,axis=0)/np.mean(data_Pn_squared_m2,axis=0))
# -np.log(np.mean(data_SWAPn_m2,axis=0)/np.mean(data_Pn_squared_m2,axis=0))

### Jacknife notes

In [44]:
N=data_SWAPn_m1.shape[1]-1
N

4

In [45]:
S2 = np.zeros(data_SWAPn_m1.shape)
for i in range(data_SWAPn_m2.shape[0]):
    Pn_squared_m1_col_sum_i = Pn_squared_m1_col_sum - data_Pn_squared_m1[i]
    Pn_squared_m2_col_sum_i = Pn_squared_m2_col_sum - data_Pn_squared_m2[i]
    
    SWAPn_m1_col_sum_i = SWAPn_m1_col_sum - data_SWAPn_m1[i]
    SWAPn_m2_col_sum_i = SWAPn_m2_col_sum - data_SWAPn_m2[i]
    
    S2[i] = -np.log(SWAPn_m2_col_sum_i/Pn_squared_m2_col_sum_i)
S2

array([[-0.00032105,  0.02363549,  0.00634131,  0.01528988, -0.02790087],
       [-0.00032105,  0.02364796,  0.00634247,  0.01526524, -0.02790087],
       [-0.00032105,  0.02363348,  0.00634309,  0.0152598 , -0.02790087],
       ...,
       [-0.00032105,  0.0236475 ,  0.00634159,  0.01527304, -0.02790087],
       [-0.00032105,  0.02367356,  0.00634462,  0.01525996, -0.02790087],
       [-0.00032105,  0.02364918,  0.00634268,  0.01526979, -0.02790087]])

In [46]:
S2_mean = np.mean(S2,axis=0)
S2_mean

array([-0.00032105,  0.0236476 ,  0.00634365,  0.01526571, -0.02790086])

In [47]:
N_rows = S2.shape[0]

In [48]:
S2_err = np.std(S2,axis=0)
S2_err *= np.sqrt(N_rows-1)

In [49]:
for n in range(N+1):
    print(f"<S2(n={n})> = {S2_mean[n]:0.6f} +/- {S2_err[n]:0.6f}")

<S2(n=0)> = -0.000321 +/- 0.006378
<S2(n=1)> = 0.023648 +/- 0.003633
<S2(n=2)> = 0.006344 +/- 0.001189
<S2(n=3)> = 0.015266 +/- 0.004119
<S2(n=4)> = -0.027901 +/- 0.084765


### $P(n)$

In [70]:
data_Pn_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_1000_Pn-mA2_"+str(seed)+".dat")
np.mean(data_Pn_m2,axis=0)

array([  9.221, 203.696, 626.563, 207.617,   8.075])

In [71]:
data_Pn_col_sum_m2 = np.sum(data_Pn_m2,axis=0)

In [72]:
jacknifed_Pn = np.zeros(data_Pn_m2.shape)
for i in range(data_Pn_m2.shape[0]):
    data_Pn_col_sum_m2_i = data_Pn_col_sum_m2 - data_Pn_m2[i]
        
    jacknifed_Pn[i] = data_Pn_col_sum_m2_i
jacknifed_Pn /= np.sum(jacknifed_Pn,axis=1)[:,None]

In [73]:
Pn_mean = np.mean(jacknifed_Pn,axis=0)
Pn_mean /= np.sum(Pn_mean )
N_rows_Pn = jacknifed_Pn.shape[0]
Pn_err = np.std(jacknifed_Pn,axis=0)
Pn_err *= np.sqrt(N_rows_Pn-1)

In [74]:
for n in range(4+1):
    print(f'P(n={n}) = {Pn_mean[n]:0.4f} +/- {Pn_err[n]:0.4f}')

P(n=0) = 0.0087 +/- 0.0012
P(n=1) = 0.1930 +/- 0.0050
P(n=2) = 0.5938 +/- 0.0063
P(n=3) = 0.1968 +/- 0.0054
P(n=4) = 0.0077 +/- 0.0012
