In [53]:
import matplotlib.pyplot as plt
import numpy as np

In [54]:
np.set_printoptions(precision=8)

In [55]:
path="/Users/ecasiano/Xcode/pimc/pimc/"

In [56]:
seed = 42

In [57]:
data_Pn_squared_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_PnSquared-mA1_"+str(seed)+".dat")
data_Pn_squared_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_PnSquared-mA2_"+str(seed)+".dat")

data_SWAPn_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAPn-mA1_"+str(seed)+".dat")
data_SWAPn_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAPn-mA2_"+str(seed)+".dat")

In [58]:
Pn_squared_m1_col_sum = np.sum(data_Pn_squared_m1,axis=0)
Pn_squared_m2_col_sum = np.sum(data_Pn_squared_m2,axis=0)

SWAPn_m1_col_sum = np.sum(data_SWAPn_m1,axis=0)
SWAPn_m2_col_sum = np.sum(data_SWAPn_m2,axis=0)

In [59]:
# -np.log(np.mean(data_SWAPn_m2,axis=0)/np.mean(data_Pn_squared_m2,axis=0))
# -np.log(np.mean(data_SWAPn_m2,axis=0)/np.mean(data_Pn_squared_m2,axis=0))

### Jacknife notes

In [60]:
N=data_SWAPn_m1.shape[1]-1
N

4

In [61]:
S2 = np.zeros(data_SWAPn_m1.shape)
for i in range(data_SWAPn_m2.shape[0]):
    Pn_squared_m1_col_sum_i = Pn_squared_m1_col_sum - data_Pn_squared_m1[i]
    Pn_squared_m2_col_sum_i = Pn_squared_m2_col_sum - data_Pn_squared_m2[i]
    
    SWAPn_m1_col_sum_i = SWAPn_m1_col_sum - data_SWAPn_m1[i]
    SWAPn_m2_col_sum_i = SWAPn_m2_col_sum - data_SWAPn_m2[i]
    
    S2[i] = -np.log(SWAPn_m2_col_sum_i/Pn_squared_m2_col_sum_i)
S2

array([[-0.00904984,  0.04492386,  0.0112952 ,  0.01217509, -0.27677684],
       [-0.00904984,  0.04504186,  0.01130633,  0.01193534, -0.27677684],
       [-0.00904984,  0.04490391,  0.01131235,  0.01188222, -0.27677684],
       ...,
       [-0.00904984,  0.04501208,  0.01132269,  0.01174753, -0.27677684],
       [-0.00904984,  0.04502771,  0.01132153,  0.01188014, -0.27677684],
       [-0.00904984,  0.04502353,  0.01129243,  0.01193756, -0.27677684]])

In [62]:
S2_mean = np.mean(S2,axis=0)
S2_mean

array([-0.00904983,  0.04503736,  0.01131727,  0.01193999, -0.27677635])

In [63]:
N_rows = S2.shape[0]

In [64]:
S2_err = np.std(S2,axis=0)
S2_err *= np.sqrt(N_rows-1)

In [65]:
for n in range(N+1):
    print(f"<S2(n={n})> = {S2_mean[n]:0.6f} +/- {S2_err[n]:0.6f}")

<S2(n=0)> = -0.009050 +/- 0.018761
<S2(n=1)> = 0.045037 +/- 0.011124
<S2(n=2)> = 0.011317 +/- 0.003677
<S2(n=3)> = 0.011940 +/- 0.012720
<S2(n=4)> = -0.276776 +/- 0.211703


### $P(n)$

In [646]:
data_Pn_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_1000_Pn-mA2_"+str(seed)+".dat")
np.mean(data_Pn_m2,axis=0)

array([ 101.453, 2113.422, 6260.748, 2040.486,   96.293])

In [523]:
data_Pn_col_sum_m2 = np.sum(data_Pn_m2,axis=0)

In [524]:
jacknifed_Pn = np.zeros(data_Pn_m2.shape)
for i in range(data_Pn_m2.shape[0]):
    data_Pn_col_sum_m2_i = data_Pn_col_sum_m2 - data_Pn_m2[i]
        
    jacknifed_Pn[i] = data_Pn_col_sum_m2_i
jacknifed_Pn /= np.sum(jacknifed_Pn,axis=1)[:,None]

In [525]:
Pn_mean = np.mean(jacknifed_Pn,axis=0)
Pn_mean /= np.sum(Pn_mean )
N_rows_Pn = jacknifed_Pn.shape[0]
Pn_err = np.std(jacknifed_Pn,axis=0)
Pn_err *= np.sqrt(N_rows_Pn-1)

In [526]:
for n in range(4+1):
    print(f'P(n={n}) = {Pn_mean[n]:0.4f} +/- {Pn_err[n]:0.4f}')

P(n=0) = 0.0096 +/- 0.0005
P(n=1) = 0.1991 +/- 0.0018
P(n=2) = 0.5899 +/- 0.0021
P(n=3) = 0.1923 +/- 0.0018
P(n=4) = 0.0091 +/- 0.0005
