In [183]:
import matplotlib.pyplot as plt
import numpy as np

In [184]:
np.set_printoptions(precision=8)

In [185]:
n=1 # Maybe actually n_max? 

In [186]:
path="/Users/ecasiano/Desktop/PrototypeScripts/Data/"

In [195]:
data_Pn_squared_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_PnSquared-mA1_42.dat")
data_Pn_squared_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_PnSquared-mA2_42.dat")

data = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_10000_SWAP-n"+str(n)+"_42.dat")

In [196]:
# data_Pn_squared_m1 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA1_42.dat")
# data_Pn_squared_m2 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA2_42.dat")
# data_Pn_squared_m3 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA3_42.dat")
# data_Pn_squared_m4 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA4_42.dat")

# data = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_SWAP-n"+str(n)+"_42.dat")

In [197]:
Pn_squared_m1_col_sum = np.sum(data_Pn_squared_m1,axis=0)
Pn_squared_m2_col_sum = np.sum(data_Pn_squared_m2,axis=0)
# Pn_squared_m3_col_sum = np.sum(data_Pn_squared_m3,axis=0)
# Pn_squared_m4_col_sum = np.sum(data_Pn_squared_m4,axis=0)

SWAP_col_sum = np.sum(data,axis=0)
SWAP_col_sum

array([      0., 2141826.,  192803.])

### Jacknife notes

In [198]:
S2_i = []
for i in range(data.shape[0]):
    Pn_squared_m1_col_sum_i = Pn_squared_m1_col_sum - data_Pn_squared_m1[i]
    Pn_squared_m2_col_sum_i = Pn_squared_m2_col_sum - data_Pn_squared_m2[i]
#     Pn_squared_m3_col_sum_i = Pn_squared_m3_col_sum - data_Pn_squared_m4[i]
#     Pn_squared_m4_col_sum_i = Pn_squared_m4_col_sum - data_Pn_squared_m3[i]
    
    # Swapped sites histogram for n sector
    SWAP_col_sum_i =  SWAP_col_sum - data[i]
    
    l = 2*[0]
    
#     l[0] = -np.log(SWAP_col_sum_i[1]/Pn_squared_m1_col_sum_i[n])
    l[1] = -np.log(SWAP_col_sum_i[2]/Pn_squared_m2_col_sum_i[n])
#     l[2] = -np.log(SWAP_col_sum_i[3]/Pn_squared_m3_col_sum_i[n])
#     l[3] = -np.log(SWAP_col_sum_i[4]/Pn_squared_m4_col_sum_i[n])
    
    S2_i.append(l)

S2_i = np.array(S2_i)
S2_i

array([[0.        , 0.04225766],
       [0.        , 0.04225766],
       [0.        , 0.04225766],
       ...,
       [0.        , 0.04225766],
       [0.        , 0.04225766],
       [0.        , 0.04225766]])

In [199]:
S2_mean = np.mean(S2_i,axis=0)
S2_mean

array([0.        , 0.04225767])

In [200]:
N_rows = S2_i.shape[0]

In [201]:
S2_err = np.std(S2_i,axis=0)
S2_err *= np.sqrt(N_rows-1)

In [202]:
print(f'<S2> = {S2_mean[1]:.6f} +/- {S2_err[1]:.6f}')

<S2> = 0.042258 +/- 0.034195
