In [125]:
import matplotlib.pyplot as plt
import numpy as np

In [126]:
np.set_printoptions(precision=8)

In [127]:
path="/Users/ecasiano/Xcode/pimc/pimc/TestNewSWAPn/"
! ls /Users/ecasiano/Xcode/pimc/pimc/

2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA100_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA101_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA102_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA103_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA104_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA105_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA106_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA107_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA108_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA109_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA10_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA110_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA111_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA112_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA113_42.dat
2D_32_1024_20_16.666667_1.000000_4.000000_1000_Pn-mA114_

In [128]:
seed = 42

In [129]:
data_Pn_squared_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_PnSquared-mA1_"+str(seed)+".dat")
data_Pn_squared_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_PnSquared-mA2_"+str(seed)+".dat")

data_SWAPn_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAPn-mA1_"+str(seed)+".dat")
data_SWAPn_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAPn-mA2_"+str(seed)+".dat")

In [130]:
Pn_squared_m1_col_sum = np.sum(data_Pn_squared_m1,axis=0)
Pn_squared_m2_col_sum = np.sum(data_Pn_squared_m2,axis=0)

SWAPn_m1_col_sum = np.sum(data_SWAPn_m1,axis=0)
SWAPn_m2_col_sum = np.sum(data_SWAPn_m2,axis=0)

In [131]:
# -np.log(np.mean(data_SWAPn_m2,axis=0)/np.mean(data_Pn_squared_m2,axis=0))
# -np.log(np.mean(data_SWAPn_m2,axis=0)/np.mean(data_Pn_squared_m2,axis=0))

### Jacknife notes

In [132]:
N=data_SWAPn_m1.shape[1]-1
N

4

In [133]:
S2 = np.zeros(data_SWAPn_m1.shape)
for i in range(data_SWAPn_m2.shape[0]):
    Pn_squared_m1_col_sum_i = Pn_squared_m1_col_sum - data_Pn_squared_m1[i]
    Pn_squared_m2_col_sum_i = Pn_squared_m2_col_sum - data_Pn_squared_m2[i]
    
    SWAPn_m1_col_sum_i = SWAPn_m1_col_sum - data_SWAPn_m1[i]
    SWAPn_m2_col_sum_i = SWAPn_m2_col_sum - data_SWAPn_m2[i]
    
    S2[i] = -np.log(SWAPn_m2_col_sum_i/Pn_squared_m2_col_sum_i)
S2

array([[-0.00032105,  0.02363549,  0.00634131,  0.01528988, -0.02790087],
       [-0.00032105,  0.02364796,  0.00634247,  0.01526524, -0.02790087],
       [-0.00032105,  0.02363348,  0.00634309,  0.0152598 , -0.02790087],
       ...,
       [-0.00032105,  0.0236475 ,  0.00634159,  0.01527304, -0.02790087],
       [-0.00032105,  0.02367356,  0.00634462,  0.01525996, -0.02790087],
       [-0.00032105,  0.02364918,  0.00634268,  0.01526979, -0.02790087]])

In [134]:
S2_mean = np.mean(S2,axis=0)
S2_mean

array([-0.00032105,  0.0236476 ,  0.00634365,  0.01526571, -0.02790086])

In [135]:
N_rows = S2.shape[0]

In [136]:
S2_err = np.std(S2,axis=0)
S2_err *= np.sqrt(N_rows-1)

In [137]:
for n in range(N+1):
    print(f"<S2(n={n})> = {S2_mean[n]:0.6f} +/- {S2_err[n]:0.6f}")

<S2(n=0)> = -0.000321 +/- 0.006378
<S2(n=1)> = 0.023648 +/- 0.003633
<S2(n=2)> = 0.006344 +/- 0.001189
<S2(n=3)> = 0.015266 +/- 0.004119
<S2(n=4)> = -0.027901 +/- 0.084765


### $P(n)$

In [120]:
data_Pn_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_1000_Pn-mA2_"+str(seed)+".dat")
np.mean(data_Pn_m2,axis=0)

array([  9.221, 203.696, 626.563, 207.617,   8.075])

In [ ]:
data_Pn_col_sum_m2 = np.sum(data_Pn_m2,axis=0)

In [69]:
jacknifed_Pn = np.zeros(data_Pn_m2.shape)
for i in range(data_Pn_m2.shape[0]):
    data_Pn_col_sum_m2_i = data_Pn_col_sum_m2 - data_Pn_m2[i]
        
    jacknifed_Pn[i] = data_Pn_col_sum_m2_i
jacknifed_Pn /= np.sum(jacknifed_Pn,axis=1)[:,None]

In [70]:
Pn_mean = np.mean(jacknifed_Pn,axis=0)
Pn_mean /= np.sum(Pn_mean )
N_rows_Pn = jacknifed_Pn.shape[0]
Pn_err = np.std(jacknifed_Pn,axis=0)
Pn_err *= np.sqrt(N_rows_Pn-1)

In [71]:
for n in range(4+1):
    print(f'P(n={n}) = {Pn_mean[n]:0.4f} +/- {Pn_err[n]:0.4f}')

P(n=0) = 0.0087 +/- 0.0012
P(n=1) = 0.1930 +/- 0.0050
P(n=2) = 0.5938 +/- 0.0063
P(n=3) = 0.1968 +/- 0.0054
P(n=4) = 0.0077 +/- 0.0012
