In [89]:
import matplotlib.pyplot as plt
import numpy as np

In [90]:
np.set_printoptions(precision=8)

In [91]:
n=1 # Maybe actually n_max? 

In [92]:
path="/Users/ecasiano/Desktop/PrototypeScripts/Data/"

In [93]:
data_Pn_squared_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_3.000000_1000_PnSquared-mA1_0.dat")
data_Pn_squared_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_3.000000_1000_PnSquared-mA2_0.dat")

data = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_3.000000_1000_SWAP-n"+str(n)+"_0.dat")

In [94]:
Pn_squared_m1_col_sum = np.sum(data_Pn_squared_m1,axis=0)
Pn_squared_m2_col_sum = np.sum(data_Pn_squared_m2,axis=0)

SWAP_col_sum = np.sum(data,axis=0)
SWAP_col_sum

array([     0., 213960.,  19198.])

### Jacknife notes

In [96]:
S2_i = []
for i in range(data.shape[0]):
    Pn_squared_m1_col_sum_i = Pn_squared_m1_col_sum - data_Pn_squared_m1[i]
    Pn_squared_m2_col_sum_i = Pn_squared_m2_col_sum - data_Pn_squared_m2[i]
    
    # Swapped sites histogram for n sector
    SWAP_col_sum_i =  SWAP_col_sum - data[i]
    
    l = 2*[0]
    
    l[0] = -np.log(SWAP_col_sum_i[1]/Pn_squared_m1_col_sum_i[n])
    l[1] = -np.log(SWAP_col_sum_i[2]/Pn_squared_m2_col_sum_i[n])
    
    S2_i.append(l)

S2_i = np.array(S2_i)
S2_i

array([[0.70547802, 0.64530623],
       [0.70537394, 0.64830093],
       [0.70548195, 0.64693522],
       ...,
       [0.70552563, 0.64956788],
       [0.70539174, 0.64614253],
       [0.70563024, 0.6455541 ]])

In [85]:
S2_mean = np.mean(S2_i,axis=0)
S2_mean

array([ 3.31958935, -1.6135377 ])

In [86]:
N_rows = S2_i.shape[0]

In [87]:
S2_err = np.std(S2_i,axis=0)
S2_err *= np.sqrt(N_rows-1)

In [88]:
print(f'<S2> = {S2_mean[1]:.6f} +/- {S2_err[1]:.6f}')

<S2> = -1.613538 +/- 0.025720
