In [16]:
import matplotlib.pyplot as plt
import numpy as np

In [17]:
np.set_printoptions(precision=8)

In [32]:
n=0 # Maybe actually n_max? 

In [33]:
path="/Users/ecasiano/Desktop/PrototypeScripts/Data/"

In [34]:
data_Pn_squared_m1 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_PnSquared-mA1_42.dat")
data_Pn_squared_m2 = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_PnSquared-mA2_42.dat")

data = np.loadtxt(path+"1D_4_4_2_3.300000_1.000000_4.000000_100000_SWAP-n"+str(n)+"_42.dat")

In [35]:
data.shape

(100000, 3)

In [36]:
data_Pn_squared_m1.shape,data_Pn_squared_m2.shape

((100000, 5), (100000, 5))

In [37]:
# data_Pn_squared_m1 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA1_42.dat")
# data_Pn_squared_m2 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA2_42.dat")
# data_Pn_squared_m3 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA3_42.dat")
# data_Pn_squared_m4 = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_PnSquared-mA4_42.dat")

# data = np.loadtxt(path+"1D_8_8_4_3.300000_1.000000_3.000000_10000_SWAP-n"+str(n)+"_42.dat")

In [38]:
Pn_squared_m1_col_sum = np.sum(data_Pn_squared_m1,axis=0)
Pn_squared_m2_col_sum = np.sum(data_Pn_squared_m2,axis=0)
# Pn_squared_m3_col_sum = np.sum(data_Pn_squared_m3,axis=0)
# Pn_squared_m4_col_sum = np.sum(data_Pn_squared_m4,axis=0)

SWAP_col_sum = np.sum(data,axis=0)
SWAP_col_sum

array([       0., 18255618.,    49844.])

### Jacknife notes

In [39]:
np.sum(SWAP_col_sum),np.sum(Pn_squared_m2_col_sum)

(18305462.0, 225381759.0)

In [40]:
S2_i = []
for i in range(data.shape[0]):
    Pn_squared_m1_col_sum_i = Pn_squared_m1_col_sum - data_Pn_squared_m1[i]
    Pn_squared_m2_col_sum_i = Pn_squared_m2_col_sum - data_Pn_squared_m2[i]
#     Pn_squared_m3_col_sum_i = Pn_squared_m3_col_sum - data_Pn_squared_m4[i]
#     Pn_squared_m4_col_sum_i = Pn_squared_m4_col_sum - data_Pn_squared_m3[i]
    
    # Swapped sites histogram for n sector
    SWAP_col_sum_i =  SWAP_col_sum - data[i]

    l = 2*[0]
    
    l[0] = -np.log(SWAP_col_sum_i[1]/Pn_squared_m1_col_sum_i[n])
    l[1] = -np.log(SWAP_col_sum_i[2]/Pn_squared_m2_col_sum_i[n])
#     l[2] = -np.log(SWAP_col_sum_i[3]/Pn_squared_m3_col_sum_i[n])
#     l[3] = -np.log(SWAP_col_sum_i[4]/Pn_squared_m4_col_sum_i[n])
    
    S2_i.append(l)

S2_i = np.array(S2_i)
S2_i

array([[-5.47793444e-05, -3.21053057e-04],
       [-5.39029133e-05, -3.21053057e-04],
       [-5.30266552e-05, -3.21053057e-04],
       ...,
       [-5.25886201e-05, -3.21053057e-04],
       [-5.26977957e-05, -3.21053057e-04],
       [-5.38479614e-05, -3.21053057e-04]])

In [41]:
S2_mean = np.mean(S2_i,axis=0)
S2_mean

array([-5.40122294e-05, -3.21052986e-04])

In [42]:
N_rows = S2_i.shape[0]

In [43]:
S2_err = np.std(S2_i,axis=0)
S2_err *= np.sqrt(N_rows-1)

In [44]:
print(f'<S2> = {S2_mean[1]:.6f} +/- {S2_err[1]:.6f}')

<S2> = -0.000321 +/- 0.006378
