In [11]:
import matplotlib.pyplot as plt
import numpy as np

In [12]:
np.set_printoptions(precision=8)

In [13]:
data = np.loadtxt("4_4_2_1D_3.300000_2.000000_1.000000_30000000000_42_can_Pn_squared2-mA.dat")
data
Zn_raw = np.sum(data,axis=0)
Zn_raw

array([1.0135000e+04, 4.1991630e+06, 3.8344823e+07, 4.2163780e+06,
       1.0545000e+04])

### $\beta$-scaling (but the original estimator)

In [14]:
n=2

In [15]:
data = np.loadtxt("4_4_2_1D_3.300000_2.000000_1.000000_30000000000_42_can_SWAP_"+str(n)+"-n-sector.dat")
np.shape(data)
data[:4]
data.shape[0]

20829

In [16]:
-np.log(np.sum(data,axis=0)[2] / Zn_raw[n])

0.005021843470353617

In [7]:
P = np.sum(data,axis=0)
P

array([       0.,  3255689., 38152744.])

In [8]:
pj = np.zeros(data.shape)

In [9]:
for i in range(data.shape[1]):
    pj[:,i]=P[i]
pj

array([[       0.,  3255689., 38152744.],
       [       0.,  3255689., 38152744.],
       [       0.,  3255689., 38152744.],
       ...,
       [       0.,  3255689., 38152744.],
       [       0.,  3255689., 38152744.],
       [       0.,  3255689., 38152744.]])

In [10]:
data

array([[   0.,  195., 1808.],
       [   0.,  203., 1826.],
       [   0.,  193., 1823.],
       ...,
       [   0.,  146., 1898.],
       [   0.,  125., 2387.],
       [   0.,  135., 1967.]])

In [48]:
N_rows = data.shape[0]
pj_bar = (pj-data)/(N_rows-1)

In [49]:
D = 1
l_A = 2
m_A = l_A**D
S = -np.log(pj_bar[:,m_A]/pj_bar[:,0])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [50]:
S_mean = np.mean(S)
S_mean

-inf

In [10]:
S_err = np.sqrt(N_rows-1)*np.std(S)
S_err

0.05213730947729768

In [11]:
print(f'<S2> = {S_mean:.6f} +/- {S_err:.6f}')

<S2> = 1.111824 +/- 0.052137
